Editor: make use of minCharCount and clearOnSelection of autocomplete component
geonetwork/geonetwork-ui pull request #1036
Opened 2024-11-12 07:37 UTC by Angi-Kinas

### Description

This PR uses the functionality of the autocomplete component to achieve the following behaviour for the keyword edition:

- When the user chooses a result, the typed characters should be cleaned
- When the user clears the input, the dropdown is closed

### Quality Assurance Checklist

- [ ] Commit history is devoid of any _merge commits_ and readable to facilitate reviews
- [ ] If **new logic** ⚙️ is introduced: unit tests were added
- [ ] If **new user stories** 🤏 are introduced: E2E tests were added
- [ ] If **new UI components** 🕹️ are introduced: corresponding stories in Storybook were created
- [ ] If **breaking changes** 🪚 are introduced: add the `breaking change` label
- [ ] If **bugs** 🐞 are fixed: add the `backport <release branch>` label
- [ ] The [documentation website](docs) 📚 has received the love it deserves

2024-11-14 10:45 UTC, cmoinier requested changes
Thanks for the work :)

However, while the changes work for the second point (closing the dropdown on clear), it doesn't work for the first one. Here I typed "asia" & selected the keyword, but the typed text wasn't cleared.

![image](https://github.com/user-attachments/assets/83727d69-6ceb-4eca-9db2-258d554627db)

2024-11-25 14:51 UTC, Angi-Kinas commented
@cmoinier thanks for the review and testing!
You are right, the clearing of the input field did not work after selection. I fixed this now.
While testing I encountered a different bug though. 
When selecting a keyword and clicking inside the input field again, the previous selected keyword is being saved as search query and therefore the dropdown suggestions only reflect the previous selected keyword.
This happens just for the keywords (not for the spatial extent keywords).
Until now I could not figure out why this is happening.

2024-12-08 03:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/geonetwork/geonetwork-ui?pullRequest=1036) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/geonetwork/geonetwork-ui?pullRequest=1036) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: cmoinier<br/>:x: Angi-Kinas<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/geonetwork/geonetwork-ui?pullRequest=1036) it.</sub>

2024-12-10 10:57 UTC, tkohr approved these changes
Thanks for the fix @Angi-Kinas ! Works like a charm. Happy to see it needed less logic than expected :-)

2024-12-10 10:57 UTC, tkohr commented on apps/metadata-editor-e2e/src/e2e/edit.cy.ts
>          it('should add a keyword', () => {
Could it make sense to add a test, which checks that the input is cleared on selection?

2024-12-10 10:57 UTC, tkohr commented on libs/feature/editor/src/lib/components/generic-keywords/generic-keywords.component.html
> +    [preventCompleteOnSelection]="false"
I see `false` is the default value, but it might indeed be more explicit to set it here.

2024-12-12 14:18 UTC, tkohr commented
Thanks for the added test! LGTM

2024-12-12 14:41 UTC, merged