Datahub: add a map to preview data on dataset view
geonetwork/geonetwork-ui pull request #156
Opened 2021-09-21 08:00 UTC by jahow

This PR introduces a new smart component calls `DataPreviewMapComponent`, which is bound to the `mdView` feature state. When a metadata is opened, the component will look for the first available link that can be rendered on a map and show it, alongside a dropdown to switch to other links.

Remaining to do:
- [ ] handle translation for placeholder value
- [ ] hide map if no valid layer can be rendered in it

![image](https://user-images.githubusercontent.com/10629150/134134154-4454ce1e-3c61-46f1-86ba-d20b550a948a.png)

2021-09-21 09:13 UTC, fgravin requested changes
Very good and excellent testing.
I think it can be improved though with some helpers, and maybe by centralizing the links computation, and make it configurable.
Also the component tree structure should be discussed.
Thanks

2021-09-21 09:13 UTC, fgravin commented on apps/datahub/src/app/dataset-view/dataset-view.component.html
> +<gn-ui-metadata-full-view></gn-ui-metadata-full-view>
`metadata-full-view` was the larger container, and NOT the information tab or whereever you put the abstract and the preview map.
We must define a clear treeview, let's discuss about that.
- metadata(dataset)-view (the whole view)
  - summary
    - metadata-info
    - dataset-preview
  - data table
  - map
  - exports
  - apis

or something like this.
In my PR, i put the tabs in `ui-metadata-full-view`

2021-09-21 09:13 UTC, fgravin commented on apps/datahub/src/app/app.component.html
> +    <gn-ui-dataset-view *ngIf="isRecordOpened$ | async"> </gn-ui-dataset-view>
I think this needs some refactoring.
`dataset-view` is the larger container for the metadata view ?

2021-09-21 09:13 UTC, fgravin commented on libs/feature/search/src/lib/metadata-view/data-preview-map/data-preview-map.component.ts
> +  dropdownChoices$ = this.availableLinks$.pipe(
this list is not customizable.
`availableLinks` should be in a service/class which could be extended ?
Not mandatory for now.

2021-09-21 09:26 UTC, fgravin commented
![Screenshot from 2021-09-21 11-25-40](https://user-images.githubusercontent.com/1491924/134146591-a9ba3459-cf6f-4d4f-a17a-1a2db126f5dc.png)

- does not display WFS data.
- overlap with the link boxes (does not really matter cause anyway we will rework the whole styling after UX, hopefully).

2021-09-21 09:37 UTC, jahow commented
> does not display WFS data.

I know, I think implementing data fetching should be part of another PR (besides this was not requested in the user story).

> overlap with the link boxes (does not really matter cause anyway we will rework the whole styling after UX, hopefully).

Exactly. The float thing was just eye candy but really the whole layout is completely provisional.

2021-09-21 09:43 UTC, fgravin commented
> I know, I think implementing data fetching should be part of another PR (besides this was not requested in the user story).
> 
> >

yes I agree, I think the logic in this PR is good, could be slighlty improved though. But the whole data fetching stuff are a bit out of scope.

2021-09-27 16:36 UTC, jahow commented
I've rebased this PR but hasn't changed much, waiting on #157 (no pressure @tkohr ;D) to go forward

2021-10-05 14:58 UTC, jahow reviewed
Looking good, thanks for picking this up! I think we can merge this and move forward with WFS and geojson later on

2021-10-05 14:58 UTC, jahow commented on apps/datahub/src/app/dataset-view/record-view.component.ts
> +      setTimeout(() => this.mapManager.map.updateSize(), 0)
this brings back memories... Ideally the map presentation component should be able to do that itself by using e.g. [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

2021-10-05 14:58 UTC, jahow commented on apps/datahub/src/app/dataset-view/record-view.component.ts
> +    map((links) => !!links && links.length > 0)
this observable should not emit anything other than arrays... this may be why also there are sometimes errors when opening a record

2021-10-05 14:58 UTC, jahow commented on apps/datahub/src/app/dataset-view/record-view.component.ts
> +    map((links) => !!links && links.length > 0)
but this can be addressed in another PR I guess

2021-10-06 13:46 UTC, merged