Recognize JPG type to display in download list
geonetwork/geonetwork-ui pull request #180
Opened 2021-11-10 09:40 UTC by tkohr

2021-11-10 10:37 UTC, fgravin commented
Thanks @tkohr, please add a description, with an exemple of a failing link (you can take the one i wrote in Jira).
Also, you must add a test which would break without your fix and which now passes.

Thanks

2021-11-15 13:24 UTC, tkohr commented
Yes right @fgravin, I added the missing tests for the file types.

2021-11-15 16:13 UTC, fgravin requested changes
minor comment but it looks good to me thanks.
You'll have to wait for the big refactoring PR to be merged and then update your PR accordingly, sorry for that.

2021-11-15 16:13 UTC, fgravin commented on libs/feature/record/src/lib/links/link-utils.spec.ts
>        it('returns download format', () => {
```suggestion
      it('returns csv format', () => {
```

2021-11-15 16:13 UTC, fgravin commented on libs/feature/record/src/lib/links/link.fixtures.ts
> +export const LINK_FIXTURES = {
good !

2021-11-16 13:03 UTC, tkohr commented
You are right @fgravin, the description wasn't quite clear. Updated that, rebased and integrated your suggestion. If CI ends up green and you are ok with it, ready to merge I think.

2021-11-16 17:54 UTC, fgravin approved these changes

2021-11-17 10:22 UTC, merged