[WIP] Document project versioning & push artifacts for applications
geonetwork/geonetwork-ui pull request #286
Opened 2022-07-07 08:25 UTC by jahow

2022-07-07 13:31 UTC, juanluisrp requested changes

2022-07-07 14:37 UTC, jahow commented on .github/workflows/artifacts.yml
> +          BASE_64_TOKEN=$(echo '{"username":"${{ secrets.DOCKER_HUB_USERNAME }}","password":"${{ secrets.DOCKER_HUB_PASSWORD }}","auth":"","email":"geonetworkbot@geonetwork-opensource.org"}' | base64
:+1:

2022-07-07 14:38 UTC, jahow commented
@juanluisrp looks to be working fine for push & release events; for the branch deletion I couldn't test it since it needs the workflow to be on the default branch to be triggered...

Any further suggestions?

2022-07-07 16:31 UTC, jahow commented on .github/workflows/artifacts.yml
> +          echo ::set-output name=DOCKER_AUTH::${BASE_64_TOKEN}
I've removed the quotes since they were causing the output to appear in the logs

2022-07-13 07:17 UTC, fgravin approved these changes
Excellent work.
Very good workflow and documentation on how to use gn-ui applications.
Thanks a lot for this contribution.

2022-07-13 07:17 UTC, fgravin commented on apps/datafeeder/README.md
> +You can build a docker image of the Datahub application like so:
Datafeeder

2022-07-13 10:28 UTC, merged

2022-07-13 10:28 UTC, jahow commented
Thanks for the reviews!

2022-07-18 09:09 UTC, fvanderbiest commented on .github/workflows/artifacts.yml
> +    name: Delete docker images for a deleted branch
:+1: excellent idea ! cc @pmauduit