Load more on aggregation
geonetwork/geonetwork-ui pull request #49
Opened 2020-11-09 15:50 UTC by LHBruneton-C2C

Add action and effect to load more on one aggregation
Output from dumb component
Dispatch action from container

2021-01-04 11:22 UTC, fgravin requested changes
Looks great except one thing to change in the new Action.
Can't test it cause the api has changed on titellus.

2021-01-04 11:22 UTC, fgravin commented on libs/search/src/lib/state/reducer.ts
> +      clone[action.key].terms.size += 20
no logic in reducers, `20` should be in the payload.

2021-01-06 12:53 UTC, fgravin commented
Great @LHBruneton-C2C, since the rebase, load more action set the `response.aggs` instead of patching it.
Also, see if you can just load the extra items instead of loading them all, using the `from` and size` `search options.
Thanks

2021-01-07 10:20 UTC, LHBruneton-C2C commented
On rebasing, I saw that there was a dependency from lib-ui to lib-search, in facet-block component, `import { AggregationsTypesEnum } from '../../../../../search/src/lib/facets/facets.model'` => is it OK ?

2021-01-07 11:54 UTC, fgravin commented
> On rebasing, I saw that there was a dependency from lib-ui to lib-search, in facet-block component, `import { AggregationsTypesEnum } from '../../../../../search/src/lib/facets/facets.model'` => is it OK ?

not it's not
model should be shared if needed

2021-01-07 11:55 UTC, fgravin approved these changes
Excellent thanks

2021-01-07 11:55 UTC, merged