docs: add a datafeeder docker comp + edit documentation
geonetwork/geonetwork-ui pull request #591
Opened 2023-08-25 11:06 UTC by f-necas

2023-08-28 15:46 UTC, jahow requested changes
Thanks, great work! I think you can organize things to make it simpler and avoid repetitions, see my comments.

I've tried locally and the datafeeder actually runs, well done for setting up a minimal datadir! Also thanks for adding documentation :pinched_fingers: 

Last thing, I had an error at the end of the submit process:
```
Error publishing the following datasets:
aerodromePolygon: java.net.UnknownHostException: geonetwork
```

I haven't looked further, if you can reproduce as well then maybe we should investigate more. But this is already very good.
```

2023-08-28 15:46 UTC, jahow commented on support-services/datafeeder/docker-compose.yml
I think you could make this file into an "extension" of the original file:
* call it `docker-compose.datafeeder.yml`
* put it in the same folder as the main one
* to use it, call `docker compose -f docker-compose.yml docker-compose.datafeeder.yml up`

This then means that you don't have to duplicate the `database`, `geonetwork` and `elasticsearch` services.

2023-08-28 15:46 UTC, jahow commented on proxy-config-dev.js
> +  },
I think you can just put this in the `proxy-config.js` file instead?

2023-08-28 15:46 UTC, jahow commented on support-services/datafeeder/datadir/console/cities.geojson
Do we really need this file? or at least can we make it smaller?

2023-08-28 15:46 UTC, jahow commented on proxy-config-dev.js
> +      'sec-org': 'camptocamp',
Maybe use a more neutral org here :wink:

2023-08-28 15:46 UTC, jahow commented on proxy-config-dev.js
> +      'sec-orgname': 'camptocamp',
see above

2023-08-29 07:37 UTC, fvanderbiest commented on docs/apps/datafeeder.md
> +"Datafeeder" is a geOrchestra's backend RESTful service to upload file based datasets and publish them to GeoServer and GeoNetwork in one shot.
"Datafeeder" is geOrchestra's backend RESTful service

2023-08-29 07:39 UTC, fvanderbiest commented on support-services/datafeeder/datadir/console/cities.geojson
Indeed, a single feature will be enough for the purpose

2023-08-29 07:40 UTC, fvanderbiest commented on support-services/datafeeder/datadir/datafeeder/frontend-config.json
> +  "thesaurusUrl": "https://dev.geo2france.fr/geonetwork/srv/api/registries/vocabularies/search?type=CONTAINS&thesaurus=external.theme.httpinspireeceuropaeutheme-theme&rows=200&q=${q}&uri=**&lang=${la
do we really want to rely on dev.geo2france.fr ? rather a local service

2023-08-29 07:42 UTC, fvanderbiest commented on support-services/datafeeder/datadir/default.properties
> +domainName=georchestra.test.org
I think you should keep the original contents of defaults.properties, as it will be easier in the future to keep them in sync.

2023-09-21 07:51 UTC, jahow approved these changes
Thanks for the work! if you can make sure that cities.geojson is smaller then it's all good!!

2023-09-21 12:22 UTC, merged