Facets search query
geonetwork/geonetwork-ui pull request #62
Opened 2020-11-23 16:40 UTC by LHBruneton-C2C

Add / remove facet to query on item selected change

TODO: change checkbox selection according to state.

2020-11-25 14:48 UTC, fgravin requested changes
As discussed, the object `params.facets` in the search state is redundant.
Facet actions should update `params.filter`, I think I missed that from the previous PR.
Also, your facet object was missing the index key (eg `tag`).

2020-11-25 14:48 UTC, fgravin commented on libs/search/src/lib/state/reducer.spec.ts
> +  describe('SetResultsAggregations action', () => {
```suggestion
  describe('SetConfigAggregations action', () => {
```

2020-12-22 11:13 UTC, fgravin approved these changes
Thanks for the work.
I'm going to test it and merge it, maybe I will do some adjustments but it's fine overall.

2020-12-22 11:13 UTC, fgravin commented on libs/search/src/lib/facets/facets-container/facets-container.component.ts
> +  findSelectedPaths(filters) {
those functions diserve tests

2020-12-22 13:46 UTC, fgravin commented
replaced by https://github.com/geonetwork/geonetwork-ui/pull/79

2020-12-22 13:46 UTC, closed without merging

2020-12-23 07:58 UTC, LHBruneton-C2C commented on libs/search/src/lib/elasticsearch/elasticsearch.service.ts
> +    const clone = JSON.parse(JSON.stringify(filters))
I needed to do a deep copy to remove immutability from the state object. Does this syntax remove it too ?

2020-12-23 09:28 UTC, fgravin commented on libs/search/src/lib/elasticsearch/elasticsearch.service.ts
> +    const clone = JSON.parse(JSON.stringify(filters))
No it's not recursive. But in this particular case you cloned it just to remove the `any` property, seems to work with my changes.