[datafeeder]: Local storage
geonetwork/geonetwork-ui pull request #98
Opened 2021-02-03 09:22 UTC by y-vynohradov

refactor: Change local storage structure

2021-02-03 13:59 UTC, fgravin requested changes
Quite good but not exactly the good structure still.
Please add some test as well.

Also I don't really understand the purpose to store the step in the localStorage as it is already in the url, explain me you approach please.

Thanks

2021-02-03 13:59 UTC, fgravin commented on libs/editor/src/lib/services/wizard.service.ts
> +    const savedWizardData = localStorage.getItem(id)
almost, the id of the batch should not be ids of the localStorage, but ids of the dictionnary stored in the localStorage
```js
localStorage
 - datafeeder-state: {
     d7c14181-2e66-49ff-868e-8c55671f955f: [{},{}]...,     
     trtrez543534543543534: [{},{}]...,
}
```

2021-02-03 13:59 UTC, fgravin commented on libs/editor/src/lib/services/wizard.service.ts
> +    const data = {
why do you save the step exactly ? how is using it ?

2021-02-03 13:59 UTC, fgravin commented
Also please rebase on master, thanks

2021-02-05 09:53 UTC, fgravin requested changes
Thanks for the refactoring.
You should add some tests please.

2021-02-05 09:53 UTC, fgravin commented on libs/editor/src/lib/components/wizard-summarize/wizard-summarize.component.spec.ts
> +const wizardServiceMock = {
good !
but you should test that it is called with the correct params.

2021-02-05 09:53 UTC, fgravin commented on libs/editor/src/lib/services/wizard.service.ts
> +  constructor(private translateService: TranslateService) {}
please add tests in this service, where you mock the localStorage

2021-02-24 06:55 UTC, tonio commented
Integrated into #103

2021-02-24 06:55 UTC, closed without merging