[ME]: Filter out place keywords in keyword section
geonetwork/geonetwork-ui pull request #987
Opened 2024-09-09 10:11 UTC by Angi-Kinas

### Description

This PR fixes the issue that place keywords were shown twice in the editor. Once in the spatial extent section and once on the third page in the keyword section.
Now the keywords are **visually** separated.

Note:
It is still important to save ALL keywords in the record in the "keywords" property.

### Quality Assurance Checklist

- [ ] Commit history is devoid of any _merge commits_ and readable to facilitate reviews
- [ ] If **new logic** ⚙️ is introduced: unit tests were added
- [ ] If **new user stories** 🤏 are introduced: E2E tests were added
- [ ] If **new UI components** 🕹️ are introduced: corresponding stories in Storybook were created
- [ ] If **breaking changes** 🪚 are introduced: add the `breaking change` label
- [ ] If **bugs** 🐞 are fixed: add the `backport <release branch>` label
- [ ] The [documentation website](docs) 📚 has received the love it deserves

2024-09-10 09:00 UTC, LHBruneton-C2C requested changes
Looking and working great, except the national / regional coverage keyword is displayed in the generic keywords components, and I think it should not be displayed, same as place keywords. I think you can recognize those specifically from the form fields config.

2024-09-10 16:23 UTC, Angi-Kinas commented on libs/feature/editor/src/lib/components/record-form/form-field/form-field-spatial-extent/form-field-spatial-extent.component.ts
> +    const notPlaceKwAndSpatialScopeKw = await firstValueFrom(
Sorry, I couldn't find a better name...

2024-09-10 16:26 UTC, Angi-Kinas commented
@LHBruneton-C2C  I filtered out the national / regional keyword from the keywords list on the editor form (visually), but kept them in the record.
I hope this is how it is supposed to be for the user. It doesn't make the code simpler though :sweat_smile:

2024-09-11 07:13 UTC, LHBruneton-C2C approved these changes
Maybe not simpler, but that's the expected behavior, thanks!

2024-09-11 15:45 UTC, merged